version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "${WEAVIATE_BIND_HOST:-127.0.0.1}:8080:8080"
      - "${WEAVIATE_BIND_HOST:-127.0.0.1}:50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_APIKEY_ENABLED: 'false'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      CLUSTER_HOSTNAME: weaviate
    volumes:
      - weaviate_data:/var/lib/weaviate
volumes:
  weaviate_data:
